#!/usr/bin/env python3

# Pentagonal numbers are generated by the formula Pn = (3n - 1) / 2.  The
# first ten pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8.  However, their
# difference, 70 - 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
# difference is pentagonal and D = |Pk - Pj| is minimized; what is D?

def pentagonals_below(n):
    i = 1
    p = 1
    while p < n:
        yield p
        i += 1
        p = i * (3 * i - 1) // 2

pents = list(pentagonals_below(100000000))
pents_set = set(pents)

d_min = -1
for n in pents:
    for m in pents:
        if m > n and m + n in pents_set and m - n in pents_set:
            d = m - n
            if d_min < 0 or d > d_min:
                d_min = d
print(d_min)
