#!/usr/bin/env python3

# Triangle, pentagonal, and hexagonal numbers are generated by the following
# formulae:
#
# Tn = n * (n + 1) / 2
# Pn = n * (3 * n - 1) / 2
# Hn = n * (2 * n - 1)
#
# It can be verified that T285 = P165 = H143 = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.

def pentagonals_below(n):
    i = 1
    p = 1
    while p < n:
        yield p
        i += 1
        p = i * (3 * i - 1) // 2

def hexagonals_below(n):
    i = 1
    h = 1
    while h < n:
        yield h
        i += 1
        h = i * (2 * i - 1)

ps = set(pentagonals_below(1000000000000))
hs = set(hexagonals_below(1000000000000))
for i in range(285, 100000000):
    tn = i * (i + 1) // 2
    if tn in ps and tn in hs:
        print(tn)
        if tn > 40755:
            break
